// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quanda.Models;

namespace Quanda.Migrations
{
    [DbContext(typeof(QuandaDbContext))]
    [Migration("20200427201016_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Quanda.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Created = new DateTime(2020, 4, 27, 15, 10, 15, 849, DateTimeKind.Local).AddTicks(353),
                            Edited = new DateTime(2020, 4, 27, 15, 10, 15, 850, DateTimeKind.Local).AddTicks(8735),
                            QuestionText = "About First Question",
                            QuestionTitle = "First Question"
                        },
                        new
                        {
                            QuestionId = 2,
                            Created = new DateTime(2020, 4, 27, 15, 10, 15, 850, DateTimeKind.Local).AddTicks(9171),
                            Edited = new DateTime(2020, 4, 27, 15, 10, 15, 850, DateTimeKind.Local).AddTicks(9192),
                            QuestionText = "About Second Question",
                            QuestionTitle = "Second Question"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
